[project]
name = "cpp-function-analyzer"
version = "0.1.0"
description = "A tool to list functions and class methods from C++ files"
authors = [
    {name = "Dev",email = "dev@example.com"}
]
readme = "README.md"
requires-python = "^3.8"
dependencies = [
    "regex (>=2024.11.6,<2025.0.0)"
]

[tool.poetry.scripts]
cpp-function-analyzer = "cpp_function_analyzer:main"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
